query Stream($id: String!, $limit: Int!) {
  stream(id: $id) {
    id
    name
    role
    branches (limit: $limit) {
      totalCount
      items {
        id
        name
        commits {
          totalCount
          items {
            id
            message
            referencedObject
          }
        }
      }
    }
  }
}
