query Streams($cursor: String, $query: String) {
  streams(cursor: $cursor, query: $query, limit: 10) {
    totalCount
    cursor
    items {
      id
      name
      description
      role
      isPublic
      createdAt
      updatedAt
      collaborators {
        id
        name
        company
        avatar
        role
      }
      commits {
        totalCount
      }
      branches {
        totalCount
      }
    }
  }
}
