query Stream($id: String!) {
  stream(id: $id) {
    id
    name
    role
    branches {
      totalCount
      items {
        id
        name
        commits {
          totalCount
          items {
            id
            message
          }
        }
      }
    }
  }
}
